# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1736sNir0Ch9iboJrypdzMvQQSlESlu-d
"""

import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import seaborn as sns

# 🎯 Load model + transformers
model = joblib.load("churn_model.pkl")
scaler = joblib.load("scaler.pkl")
imputer = joblib.load("imputer.pkl")
model_columns = joblib.load("columns.pkl")

st.set_page_config(page_title="Universal Churn Predictor", layout="wide")
st.title("📉 Universal Customer Churn Prediction Dashboard")

uploaded_file = st.file_uploader("📂 Upload your customer CSV file", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    st.success("✅ File uploaded!")

    # Show preview
    st.dataframe(df.head())

    # Process file
    raw_input = pd.get_dummies(df)
    for col in model_columns:
        if col not in raw_input:
            raw_input[col] = 0  # add missing

    raw_input = raw_input[model_columns]  # align column order
    imputed = imputer.transform(raw_input)
    scaled = scaler.transform(imputed)

    # Predict
    predictions = model.predict(scaled)
    df['Predicted Churn'] = predictions

    # 📊 Visualizations
    st.subheader("🔍 Churn Prediction Breakdown")
    st.dataframe(df)

    st.subheader("📊 Churn Distribution Pie Chart")
    pie_data = df['Predicted Churn'].value_counts()
    fig1, ax1 = plt.subplots()
    ax1.pie(pie_data, labels=pie_data.index, autopct='%1.1f%%', startangle=90, colors=["skyblue", "lightcoral"])
    ax1.axis('equal')
    st.pyplot(fig1)

    st.download_button("⬇️ Download Predictions CSV", df.to_csv(index=False), "predictions.csv")
